use rmcp::handler::server::wrapper::Parameters;
use rmcp::{RoleServer, ServerHandler, ServiceExt, tool, tool_router};
use std::path::PathBuf;
use std::sync::Arc;
use tokio::io::{stdin, stdout};

use rmcp::ErrorData;
use rmcp::model::{
    CallToolRequestParams, CallToolResponse, ListResourcesResult, ListToolsResult,
    PaginatedRequestParams, ReadResourceRequestParams, ReadResourceResponse, ReadResourceResult,
    Resource as MCPResource, ResourceContents, ResourcesCapability, ServerConfig,
};
use rmcp::service::RequestContext;

use crate::resources::vault::{ResourceError, ResourceManager};
use crate::tools::echo::{self, EchoParams};

/* Tools Implementation */
#[derive(Clone)]
struct Tools;

#[tool_router(server_handler)]
impl Tools {
    #[tool(description = "Echoes a message back to the user")]
    async fn echo(
        &self,
        Parameters(args): Parameters<EchoParams>,
    ) -> Result<String, rmcp::ErrorData> {
        echo::run(args).await
    }
}

/* Server/Resources Implementation */
#[derive(Clone)]
struct Server {
    vault_manager: Arc<ResourceManager>,
    tools: Tools,
}

impl ServerHandler for Server {
    fn get_info(&self) -> ServerConfig {
        // 1. Get the base configuration generated by the macro on MyTools
        // This automatically includes your tool capabilities!
        let mut info = ServerHandler::get_info(&self.tools);

        // 3. Explicitly tell the client we support Resources too!
        info.capabilities.resources = Some(ResourcesCapability::default());

        info
    }

    /* Tools */

    async fn list_tools(
        &self,
        req: Option<PaginatedRequestParams>,
        ctx: RequestContext<RoleServer>,
    ) -> Result<ListToolsResult, ErrorData> {
        // Forward the request to the macro-generated handler on MyTools
        ServerHandler::list_tools(&self.tools, req, ctx).await
    }

    async fn call_tool(
        &self,
        req: CallToolRequestParams,
        ctx: RequestContext<RoleServer>,
    ) -> Result<CallToolResponse, ErrorData> {
        // Forward the request to the macro-generated handler on MyTools
        ServerHandler::call_tool(&self.tools, req, ctx).await
    }

    /* Resources */

    /// Handles the `resources/list` MCP endpoint
    async fn list_resources(
        &self,
        _req: Option<PaginatedRequestParams>,
        _ctx: RequestContext<RoleServer>,
    ) -> Result<ListResourcesResult, ErrorData> {
        let custom_resources = self.vault_manager.list_resources();

        let mcp_resources = custom_resources
            .into_iter()
            .map(|r| {
                let mut res = MCPResource::new(r.uri, r.name);
                res.mime_type = r.mime_type;
                res.description = r.description;
                res
            })
            .collect();

        Ok(ListResourcesResult {
            resources: mcp_resources,
            ..Default::default()
        })
    }

    /// Handles the `resources/read` MCP endpoint
    async fn read_resource(
        &self,
        req: ReadResourceRequestParams,
        _ctx: RequestContext<RoleServer>,
    ) -> Result<ReadResourceResponse, ErrorData> {
        match self.vault_manager.read_resource(&req.uri) {
            Ok(content) => {
                let text_content = ResourceContents::text(content.uri, content.text);

                let result = ReadResourceResult::new(vec![text_content]);

                Ok(result.into())
            }
            Err(ResourceError::NotFound(uri)) => Err(ErrorData::invalid_params(
                format!("Resource not found: {}", uri),
                None,
            )),
            Err(e) => Err(ErrorData::internal_error(e.to_string(), None)),
        }
    }
}

// Configuration for the Obsidian Vault path, loaded from environment variables or testing defaults
pub struct ServerResourceConfig {
    vault_path: PathBuf,
}

impl ServerResourceConfig {
    /// Loads configuration from the environment for production use
    pub fn from_env() -> Self {
        dotenvy::dotenv().ok();
        let path_str = std::env::var("VAULT_PATH").unwrap_or_else(|_| "./vault".to_string());

        Self {
            vault_path: PathBuf::from(path_str),
        }
    }
}

// Function to start the server
pub async fn start(config: ServerResourceConfig) -> Result<(), Box<dyn std::error::Error>> {
    dotenvy::dotenv().ok();

    let transport = (stdin(), stdout());

    let vault_manager = Arc::new(ResourceManager::new(&config.vault_path)?);

    let service = Server {
        vault_manager,
        tools: Tools,
    };

    let server = service.serve(transport).await?;
    let _quit_reason = server.waiting().await?;

    Ok(())
}
